### ISSUE TITLE
ACDC dataset preprocessing on the original UNETR？

### ISSUE THREAD

**Issue by aubest** [Amshaker/unetr_plus_plus#2]
Hi, I am very interested in your work. But I'm very confused about ACDC dataset preprocessing for training the original UNETR. I will appreciate it if you could provide some relevant information.

**Comment by Amshaker** [comment]
Hi @aubest,

Thank you for being so interested in our work. 

For UNETR and UNETR++ preprocessing on the ACDC dataset, all images are first resampled to the same target spacing. Augmentations such as rotation, scaling, gaussian noise, gaussian blur, brightness and contrast adjustment, simulation of low resolution, gamma augmentation, and mirroring. The ROI crop size is 160x160x16 during the training for both models on the ACDC dataset.

Specifically, we followed the same preprocessing of [nnFormer](https://github.com/282857341/nnFormer), except that the ROI crop is 160x160x16 instead of 160x160x14.

Please let me know if you still have more questions.

Best regards,
Abdelrahman.
