### ISSUE TITLE
run_training.py

### ISSUE THREAD

**Issue by Yffy123456** [Amshaker/unetr_plus_plus#41]
Hello, when I ran the run_training.py, there is such a mistake: sitk::Error :The file"home/de/unter_plus_plus-main/DATASET/unetr_pp_-main/DATASET/unetr_pp_preprocess/Task002_Symapse/gt_segmentations/im g0025.nii.gz'does not exist.  And img0001.nii.gz.  -img0022.nii.gz in the  validation_raw is all black.

**Comment by Amshaker** [comment]
Hi @Yffy123456 ,

Thank you for your questions.

You should not run `run_training.py` directly, please download our pre-processed data as we mentioned in the readme, and run `run_training_synapse.sh` because this script set some required paths first.

Please try that and let me if you still have the same issue or not.

Best regards,
Abdelrahman.
