### ISSUE TITLE
what is before, after score??

### ISSUE THREAD

**Issue by SkiddieAhn** [Amshaker/unetr_plus_plus#7]
when I predict with your checkpoint file, I can see (foreground vs background, before score, after score) what is before, after score??

and  what's mean on below?

for which classes:
[12, 13, 2, 3, 4, 5, 6]

**Comment by Amshaker** [comment]
Hi,

Thank you for your question.

This is due to the post-processing, based on nnUNet framework.

You can find the final (mean) predictions for the validation cases in: _unetr_pp/3d_fullres/Task002_Synapse/unetr_pp_trainer_synapse__unetr_pp_Plansv2.1/fold_0/validation_raw_postprocessed/summary.json_

Thank you,
Abdelrahman.
