### ISSUE TITLE
BTCV evaluation

### ISSUE THREAD

**Issue by SkiddieAhn** [Amshaker/unetr_plus_plus#9]
I want to evaluate with BTCV test dataset (img0061.nii.gz ~ img0080.nii.gz)
But I can not evaluate with your Synapse code.
How do you evaluate with BTCV test dataset??

Thanks for reading

**Comment by Amshaker** [comment]
To evaluate with BTCV, you have to download this [json file](https://drive.google.com/file/d/1qcGh41p-rI3H_sQ0JwOAhNiQSXriQqGi/view) and train the same model of Synapse. After that, to get the results from the leaderboard, you have to register in [Multi-Atlas Labeling Beyond the Cranial Vault - Workshop and Challenge](https://www.synapse.org/#!Synapse:syn3193805/wiki/) and submit your predictions to the server.

I hope it is clear now.

Best regards.

**Comment by SkiddieAhn** [comment]
1. Can you tell me which json file located in which path I should replace with this file?

2. I don't understand how I can train with the same code. BTCV uses 24 files for training data, but Synapse uses only 18 files. Is this okay?

3. Is it okay to perform inference on the test data (61-80) without preprocessing? If preprocessing is necessary, can you explain how to do it?

4. Where should I put the test data? There are multiple paths named "imagesTs," so I'm confused. Can you explain this to me?

**Comment by Amshaker** [comment]
Hi @SkiddieAhn ,

Sorry for the late reply.

1) The json file located inside the preprocessed data, check unetr_pp_raw_data/Task_X/dataset.json.

2) For BTCV, you have to download this [json file](https://drive.google.com/file/d/1qcGh41p-rI3H_sQ0JwOAhNiQSXriQqGi/view) and place it in the dataset folder instead of dataset.json. Make sure from the printing at the beginnings, it should print "24 samples trainings not 18 samples".

3) You have to do the preprocessing, please read our paper for more information about the preprocessing, it is similar to [nnFormer](https://github.com/282857341/nnFormer)

4) There are many paths because the folder we are sharing contains the raw and pre-processed data. The testing data should be placed in imagesTs inside unetr_pp_raw/
      ├── unetr_pp_raw_data/
          ├── Task0X/
              ├── imagesTs/

After preprocessing, the cropped and the processed patches will be placed in different folders. You have also to update the trainer with the json file. Alternatively, you may write the training and testing samples in the trainer (Similair to this https://github.com/Amshaker/unetr_plus_plus/blob/0e30f5a8795ecd4f1d011662198ee33942760ca0/unetr_pp/training/network_training/unetr_pp_trainer_synapse.py#L338)

I hope it is clear now.

We might update a repo in the next month by more information regarding the preprocessing and make the pipeline more clearer.

Thank you

**Comment by 6018203135** [comment]
@SkiddieAhn 
Hello classmates! Did you reproduce the BTCV dataset with Unetr++? Do you rewrite the trainer yourself or just use the synapse code to run BTCV?

**Comment by 6018203135** [comment]
@Amshaker 
Disturbed the author! Can I use synsbe code to run the BTCV dataset? If so, where should I make changes? It seems that only changing the final number of output channels and the corresponding training and validation sets will not work.

**Comment by Amshaker** [comment]
Hi @6018203135 ,

Yes, you can use the Synapse architecture and just update the trining and validation sets (24 +6) instead of (18+12), without changing the channels. This should work

**Comment by shouwangzhe134** [comment]
> 
![image](https://github.com/Amshaker/unetr_plus_plus/assets/19248726/c77704b9-ccdf-437d-91e6-90be3df20d95)

I have submitted my results on the testing subjects to the public Jenkins build server.
All my results are not scored. I don't know what's wrong.
Can you help me? Thank you!

**Comment by shouwangzhe134** [comment]
![image](https://github.com/Amshaker/unetr_plus_plus/assets/19248726/2ca10226-d5f3-4ed7-8c95-25f08c2166f8)
Why dose the results on BTCV leaderboard is much lower than the original paper of UNETR and Swin-UNETR?

**Comment by AustinYuAo** [comment]
Hello @shouwangzhe134 , 
I noticed that you have already received a score on the leaderboard. I have also submitted my BTCV results on the official website, but I haven't received a score yet. What should I do?
